### ISSUE TITLE
Can't add Deluge to Sonarr (authentication failed)

### ISSUE THREAD

**Issue by thunderstorm654** [TechPerplexed/Gooby#83]
Hi, I'm trying to add Deluge as a download provider in Sonarr. I installed Deluge, Jackett and Sonarr successfully via the Gooby setup. I have added an indexer to Jackett fine. With all three I have done the "secure" option and set my own user/pass. When Deluge opened up I noticed although it's secured with my user and pass, Deluge still has its default password which is fine. However I went to change it, via the deluge preferences, and I think this may be where I've run into problems. Sonarr keeps saying authentication failed even when I typed in my new password.
I tried a system cleanup, which seemed to reset the Deluge password back to the default but still no joy - Sonarr always says authentication failed when I try to add it.

Any advice would be great, I'm sure it's something simple but I cannot seem to get it working! I appreciate this is not so much an issue rather than "help" but I'm stumped after reading all your docs. :)

**Comment by TechPerplexed** [comment]
So, if I understand correctly - Deluge keeps reverting back to the default password, so that Jackett/Sonarr/etc can't connect to it any longer, right?

You could try to reset the Deluge permissions: 
`sudo chown -R $USER:$USER /var/local/Gooby/Deluge`

And see if your new password will "stick" that way. Fingers crossed it's something that simple :)

**Comment by thunderstorm654** [comment]
Hi there, thanks for the reply. That didn't work, so I tried uninstalling (removing all settings) both Sonarr and Deluge, doing a system cleanup then starting again. But same thing unfortunately, it keeps saying authentication failed with the password. I did notice that deluge and Sonarr are both still "secured" from.my first attempt (user/pass prompts) so not sure if that has an impact?

**Comment by deedeefink** [comment]
Let's double check one thing. Deluge user interface can be confusing when it comes to changing password. I got lost initially and pressed "Apply" at the bottom of the settings window. But, you need to click "Change" right underneath the password input fields. Otherwise the change is not saved.

I know it sounds elementary, but let's double check anyway :-)

![deluge](https://user-images.githubusercontent.com/14345450/59496371-f0a50d80-8e99-11e9-87b0-36c32ea47bf2.png)

If that does not work, please add a screen dump of what you put into Sonarr.

**Comment by thunderstorm654** [comment]
Hi there, thanks for the reply. I don't have that option "change", I just did it via the web client though. Since I uninstalled it all and reinstalled, I have not changed the default Deluge password this time. But within the Gooby menus there is an option to "secure Deluge" which I have done. But, neither default nor that password (which wouldn't make sense anyway) work with Sonarr. I linked to a screenshot of Sonarr in the previous post. On a mobile and when I embedded the image it was huge so made it a link! :)

**Comment by deedeefink** [comment]
Okay, the screenshot I added is also from the webinterface. So if you did it the, just make sure you click "Change" before you click "Apply"

When reading your further reply, I got the hunch that you're using the two password wrong. I could be mistaken, but just in case, let me describe how they work

Overall you should keep in mind that Gooby "secure" option has nothing to do with linking/Authenticating Sonarr with Deluge

1. Deluge password is the one you should use to connect Sonarr. It can be changed in the webinterface ie. deluge.example.com.
2. Gooby "secure" username and password should not be used to connect Sonarr to Deluge. The "secure" option will add http authentication to the web server. What practically should happen is that you get a pop-up where you enter the user+pass you created BEFORE Deluge would ask you for the Deluge password.

= the above are two different things. The first is to login to Deluge, the second (Optional) is related to the web server as an extra layer of protection
= you should use Deluge password when connecting to Sonarr, not the "Secure" password

I hope it makes sense and will help :-)

**Comment by thunderstorm654** [comment]
:-) that was my understanding as well. I just wondered if securing it (the http auth) would have any impact at all on the 'other' password for Deluge itself, but I didn't think it should/would. Thanks for the confirmation on that.

I'm sure I'm doing exactly as you say, but, since it isn't working, I must have done something wrong.

I definitely don't see a 'change' option under the password by the way:
![image](https://user-images.githubusercontent.com/16837607/59500582-a6b82980-8e91-11e9-9aff-511912d83e71.png)

But, since I reinstalled Deluge, I have not changed the password from the default. 

I am trying to setup Deluge as a download client in Sonarr using the exact same password which is accepted in the Deluge prompt:
![image](https://user-images.githubusercontent.com/16837607/59500692-debf6c80-8e91-11e9-8c1a-2a1ab3d673f2.png)

So, I don't *think* I'm entering the wrong thing?!

**Comment by deedeefink** [comment]
Thanks for the clarification. An old habit of mine to to rule our these mistakes.

Does it work with the default password after you reinstalled Deluge?

btw. seems I'm running an old version of Deluge as I have the "change" button

**Comment by thunderstorm654** [comment]
It is always worth ruling out the standard mistakes! :)

No, it won't work with the default pw (deluge). 

As I'm running out of ideas, I tried changing the password again within Deluge anyway, got a nice confirmation within the Deluge UI that it had changed the password. Double checked it works when I load up the Deluge UI in another browser session.

But Sonarr still refuses to add it, always saying authentication failed. Are the host and port within Sonarr definitely meant to be deluge/8112 and all other settings as below?
![image](https://user-images.githubusercontent.com/16837607/59502341-74103000-8e95-11e9-8dc6-a22d2eea141e.png)

**Comment by deedeefink** [comment]
Looks like you filled in everything correct. I'm also running out of ideas and seems like we need @TechPerplexed to help

**Comment by thunderstorm654** [comment]
Thanks for all your help checking the config though @deedeefink :)

**Comment by TechPerplexed** [comment]
Yikes, first of all thanks @deedeefink for all your insight... I too don't have the "change" button (I updated to the latest version of Deluge since they seem to have squashed that bug they had a while ago). Just "Apply" and "Ok" at the bottom, just like @thunderstorm654... so I don't think the difference in version is what caused the bug.

Currently I'm out of options what it could be though, since @deedeefink seems to have covered all bases. I'm still wondering if it could have anything to do with the extra web security you put in place. Just to be sure, can you please remove the security files for Deluge, Sonarr, Radarr etc in the folder /var/local/Gooby/Security - then clean the system from the menu and see if your apps can talk to each other again?

It's a longshot... if that's not it, I will have to ask for expert help because then it's "above my paygrade", hahaha!

**Comment by thunderstorm654** [comment]
Damn! No still no joy @TechPerplexed. I binned the lot, removed the security files, did the system cleanup and then installed afresh.. tried connecting Sonarr and Deluge with everything as the default and same issue again. 
I even then tried the beta version of Sonarr but still the same..it must be something wrong with Deluge. But I'm at a complete loss as well - seems pretty bizarre.

**Comment by TechPerplexed** [comment]
Sorry it took so long to respond... and I'm not the bearer of good news I'm afraid. It appears that you have encountered the same bug as a friend of mine has... 

Unfortunately, he never got it to work.  For him it was intermittent, it would start working again and that would last a week or month but then start over again.  

In the end he switched to Transmission and he hasn't had issues yet. I have no experience with that myself, but if you like I can ask him for his Docker file.

**Comment by VeelaCleave** [comment]
Same problem here, fresh install on a new root server.  I had some issues with Debian, latest release.  Seems that it for some reason was trying to go to the docker link with Debian, and not debian.  Installed docker manually but now running into the issue above as well as docker containers not started on reboot.  Going to reset server and switch to ubuntu and see if I get some luck.

Just wandering if the users having problems are on Debian?

Thanks for your hard work, really looking forward to getting this up and running :)

Veela

**Comment by bdschuster** [comment]
@VeelaCleave no issues here, using newest version of Debian. Everything installed as it should on a brand new installation.

**Comment by VeelaCleave** [comment]
> @VeelaCleave no issues here, using newest version of Debian. Everything installed as it should on a brand new installation.

Strange :/  I just reset my root server, created a User and added to sudoers and getting the same Deluge Authentication problem as above, everything else seems to be working fine.  Tried latest Debian and on this occasion Ubuntu 18.10.

Not sure what's going on!

**Comment by bdschuster** [comment]
Should have been more clear, sorry, just woke up and half asleep...lol...anyways, I don't use Deluge with Sonarr or Radarr, I manually add items to it as I rarely use torrents except for finding some obscure movie or TV Show. So I was saying "everything installs as it should" for all the other problems you were having. But, I did notice something weird with Deluge, I use an app called NZB360 on my phone to manage Sonarr/Radarr/NZBGet/Delude, great app by the way, and if I haven't logged into Deluge in my browser session for about, I want to say a couple days, I get authentication issues with the app (nzb360), even though everything matches and it has worked before. BUT, if I leave my Deluge browser window up and logged in, even in the background, the app works perfectly fine untill my browser refreshes or my Deluge session expires, then I have to log back in via browser, and my app will work again. Weird, but it works. 🤷‍♂️ I will try Sonarr/Radarr later today and let you know if I'm having the issue.

**Comment by VeelaCleave** [comment]
Just a quick update, not sure if OP is still having problems,

I edited `/opt/Gooby/scripts/components/40-deluge.yaml`

Changing the line: 

` image: linuxserver/deluge:latest`

to

`image: linuxserver/deluge:amd64-78da80ca-ls20`

And it now works perfectly and connects.  Seems like the newest Deluge is having some sort of issues! Can live with an older version for now but would advise people not to update until we can figure out what's gone wrong :)

**Comment by TechPerplexed** [comment]
Thanks! I'll leave this open for a bit longer so others will see this discussion and suggested solutions, fingers crossed that this solves it for everyone!

**Comment by VeelaCleave** [comment]
> Thanks! I'll leave this open for a bit longer so others will see this discussion and suggested solutions, fingers crossed that this solves it for everyone!

No idea why the latest version doesn't work but using an older one does seem to solve the problem, will monitor releases and see if the newer release works, if/when!

**Comment by bdschuster** [comment]
I'll have to test this, cause I just looked at my Deluge, and there isn't even a place to change password anymore. I mean, my password is in the config and works, but not in the UI anymore. Strange.

**Comment by TechPerplexed** [comment]
Well friendlies, it's been 3 days and I'm really hoping this one is resolved - I shall close it for now but feel free to add or reopen if necessary :)

**Comment by bdschuster** [comment]
Sorry, forgot to reply to this when I figured some things out. Apparently Deluge changed their API format, with that being said, Sonarr/Radarr have to change the way it talks to Deluge. Sonarr has fixed this on their develop version (they call it Preview), and it does indeed work. I have actually been using Sonarr's Preview version for some time and there has been no issues. With that said, you can use the latest version of Deluge, changing back to 'deluge:latest'. Then changing Sonarr to 'sonarr:preview' in the yaml file. I am going to change this in on our end, but if you already have it installed you will need to change manually on your end, or just uninstall/install Sonarr again and it will be the correct version that works with Deluge. 

Now Radarr is another thing, they have pretty much stopped updating the old version as they are now starting to work on the new version that looks like Sonarr does, but I have tested that as well, and there are waaay to many bugs yet, including that it won't work with OMBI or sometimes won't even let you download a movie, and some pages don't even load yet. So we won't be implementing that for some time yet. 

If you have any questions or issues, let us know.

**Comment by thunderstorm654** [comment]
> Sorry, forgot to reply to this when I figured some things out. Apparently Deluge changed their API format, with that being said, Sonarr/Radarr have to change the way it talks to Deluge. Sonarr has fixed this on their develop version (they call it Preview), and it does indeed work. I have actually been using Sonarr's Preview version for some time and there has been no issues. With that said, you can use the latest version of Deluge, changing back to 'deluge:latest'. Then changing Sonarr to 'sonarr:preview' in the yaml file. I am going to change this in on our end, but if you already have it installed you will need to change manually on your end, or just uninstall/install Sonarr again and it will be the correct version that works with Deluge.
> 
> Now Radarr is another thing, they have pretty much stopped updating the old version as they are now starting to work on the new version that looks like Sonarr does, but I have tested that as well, and there are waaay to many bugs yet, including that it won't work with OMBI or sometimes won't even let you download a movie, and some pages don't even load yet. So we won't be implementing that for some time yet.
> 
> If you have any questions or issues, let us know.

Hi there, sorry I have been away so hadn't had a chance to try the suggestions. Thanks to everyone who's chipped in!

I have completely removed both Sonarr and Deluge, (including binning user settings). Then I installed the preview version of Sonarr and whatever comes with 'stable' Deluge. 

But I am still getting the same 'authentication failed' error. 

I checked the yaml files. Sonarr it says 'image: linuxserver:sonarr:preview'. Deluge it says 'image: linuxserver/deluge:latest'. Is this correct?

Thanks.

**Comment by VeelaCleave** [comment]
@thunderstorm654 check my comment above, if you change the yaml file for Deluge to: 

`image: linuxserver/deluge:amd64-78da80ca-ls20`

That will work at least until Sonarr/Radarr are all sorted :)

**Comment by thunderstorm654** [comment]
@VeelaCleave I mentioned I also tried your suggestion too, I've updated the yaml file but it doesn't make any difference... do I need to reboot or anything like that?

**Comment by VeelaCleave** [comment]
@thunderstorm654 I went to the Gooby menu and removed deluge.  I then made the changes and added deluge again, but I guess a system cleanup after making the changes should also work.

During install of deluge it'll download our specific version, the version before the major 2.0 update.  There are currently no security issues so using an older version does not appear to be a problem :)

**Comment by thunderstorm654** [comment]
@VeelaCleave Perfect!! It's now working :) Many thanks for your help!

I guess I can just leave it like that for now and hopefully in future when Sonarr sort things out, I can just change the yaml file back to 'latest'?

**Comment by VeelaCleave** [comment]
@thunderstorm654 glad it's working and yes, I would leave it like that until either someone patches sonarr/radarr or they are updated to work with the new 2.0 deluge :)

**Comment by ronyboi1** [comment]
Sorry to open this up again but I had a similar problem 30 minutes ago and I found a solution.
I changed user  "user=me" to "user =deluge" and "group=me" to "group=deluge" in  "sudo nano /etc/systemd/system/deluge-web.service" 
Sorry for my bad English, but I thought it would be important to post the solution incase someone faces a similar issue in the future.
